### ISSUE TITLE
Simple test is passing when it should fail..

### ISSUE THREAD

**Issue by akoolenbourke** [disruptorbeam/trilleon#28]
Am I doing something stupidly wrong here? Obviously the second assert should fail but the test is passing.

```
        [Automation("Saves")]
        public IEnumerator MinimalRepo()
        {
            var has = false;
            Q.assert.IsTrue(!has, "Should be false");
            Q.assert.IsTrue(has, "Should be true");
            yield return null;
        }
```

![image](https://user-images.githubusercontent.com/29034122/89169820-df095280-d5d2-11ea-9d5c-4f28708d40c1.png)

**Comment by tsibiski** [comment]
Which version of Unity are you using?

**Comment by tsibiski** [comment]
The answer: Q.assert.IsTrue is an IEnumerator. It must be in a "StartCoroutine()" wrapper. Without that logic, it simply will never run the method. It will skip over it. And because of that, no assertions were made at all, and the test passed.

**Comment by akoolenbourke** [comment]
Oh geez, Thanks - how did I miss that?!?!. Is there an equivalent method for asserting that doesn't run on a coroutine? Ideally I'd just like to run a bunch of high speed unit tests in a block of code?

**Comment by tsibiski** [comment]
That's a good idea and a pretty reasonable request... but if I recall why I did not do that, I believe it was due to my abuse of coroutines as a mean of making my automation work seemlessly without interfering with the actual game execution at all. The framework was built entirely for QA Automation first, and then UnitTesting was implemented later. Let me see if there is a way to do that which doesn't require a big ol' rewrite of the whole logic flow and I will let you know. I know its a pain from a syntax perspective, but I can guarantee that even though it is a coroutine, without QA Automation logic involved, it is not significantly less fast than normal Unit Tests. Particularly if the current scene where they are running does not have a lot of Coroutines running such that the UnitTest is waiting for Unity to hand off the Coroutine control from game logic to Trilleon logic.

Now, the reason I did this originally is that I wanted my Unit Test framework to allow you to test coroutines with zero issues, since normal Coroutine tests were impossible with the existing Unity Unit Testing. This means that your Unit Test framework allows you to access parts of the game that are required to begin Unit Tests on specific Coroutines. Or at least it allows you to setup mock situations while a game/editor is active to run those Coroutine Unit Tests. And, of course, coroutines in the test framework were required as a result. 

So it may not be possible or reasonable to modify everything to allow for Unit Tests that do not use Coroutines at all. It is a sort of trade off. Part of which is a mild performance hit. But if you ever intend to test things that require coroutines, it is worth it.

**Comment by akoolenbourke** [comment]
Thanks very much for taking the time to reply. 

I might not fully understand what your reasoning is but I don't have much of a problem with the test methods being Coroutines, just the actual asserts. So I could still have waits and things in my test methods if I wanted, but other than that then the Q.assert calls would just be tidier to look at, easier to type and quicker (I imagine) 

Again, thanks for your time.

**Comment by akoolenbourke** [comment]
Just wanted to add that I looked at the Q.assert code and it's calling StartCoroutine itself so isn't it sufficient to call
`yield return Q.assert.IsTrue(expression);` instead of `yield return StartCoroutine(Q.assert.IsTrue(expression));`

The examples say the latter should be used.
